### ISSUE TITLE
Minimum PHP version supported

### ISSUE THREAD

**Issue by scottsmith130** [publicmediaplatform/phpsdk#9]
The original intent for this SDK was to make it compatible back to PHP 5.3.  That fact is not documented anywhere, and I'm wondering what everyone thinks about changing that to PHP 5.4 as the minimum, given that PHP 5.3 is going to be end-of-life in the next few months.

**Comment by johnymonster** [comment]
It looks like this could probably be closed out, the composer.json file is setting the required minimum php version.

**Comment by cavis** [comment]
Done!

**Comment by inadarei** [comment]
http://php.net/eol.php PHP 5.3 has been EOL for a while, something to keep in mind...
